---
- name: Add a persistent environment variable to the remote user's shell.
  lineinfile:
    dest: "~/.bash_profile"
    regexp: '^ENV_VAR='
    line: 'ENV_VAR=value'
    become: false

- name: Get the value of an environment variable
  shell: 'source ~/.bash_profile && echo $ENV_VAR'
  register: foo

- name: debug
  debug: msg="The variable is {{ foo.stdout }}"

- name: ensure httpd is installed
  package: 
    name: "{{ apache_package }}"
    state: present

# Using a handler to restart apache when a test config file is copied up
- name: copy test config file.
  copy: 
    src: files/test.conf
    dest: "{{ apache_config_dir }}/test.conf"
  notify: restart apache

- name: make sure handlers are flushed immediately instead of at the end of the playbook
  meta: flush_handlers

- name: ensure httpd is running and starts at boot
  service: 
    name: "{{ apache_service }}"
    state: started
    enabled: yes